# Harmony Jekyll theme general configurations 
markdown: redcarpet

highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink:        pretty

# Base URL
baseurl: /harmony
# Site URL
#url: http://webcreate.lk/harmony
# Localhost 
url: http://localhost:4000

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Harmony #Name of your site
  description: Harmony is free responsive jekyll theme. # Little description about your site
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Gayan Virajith
    email: gayanvirajith@gmail.com
    url: http://gayanvirajith.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: gayanvirajith
    twitter: gayanvirajith
    facebook: gayanvirajith
    gplus: +GayanVirajith
    dribble: gayanvirajith
    pinterest: gayanvirajith
  # Toggle disclaimer in footer
  show_disclaimer: true
