# Harmony Jekyll theme general configuration 
markdown: redcarpet
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true
# Base URL
baseurl: /harmony
# Site URL
url: http://webcreate.lk/harmony
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore

# Sass conversion configs
sass:
    sass_dir: _includes/css/_sass
    style: :compressed

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Harmony #Name of your site
  description: Harmony is free responsive jekyll theme. # Little description about your site
  author: # Author details
    name: Gayan Virajith
    email: gayanvirajith@gmail.com
    url: http://gayanvirajith.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: gayanvirajith
    twitter: gayanvirajith
    facebook: gayanvirajith
    gplus: +GayanVirajith
    dribble: gayanvirajith
    pinterest: gayanvirajith
